Repository Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-, pull requests merged in 2024-07, with the labels that each got.

#718 Enhanced Functionality of feedback form
  index.html
Labels: gssoc, level2

#736 Added footer and fixed the navbar of RateUs Page
  rateus.css
  rateus.html
Labels: gssoc, level2

#518 added the "medicine use" page
  index.html
  medicine.css
  medicine.html
  medicine.js
Labels: gssoc, level3

#500 Added blood test page
  bootstraptest.css
  index.html
  jsconfig.json
  test.css
  test.html
  test.js
Labels: gssoc, level3

#713 fixed the links in the nav bar
  index.html
  news.html
Labels: gssoc, level1

#750 ✨[Feature Request]: Creating POPUP to blood types
  Css-Files/bloodstyle.css
  Html-Files/blood.html
  Html-Files/list.html
  js/popupbloodlist.js
Labels: gssoc, level3

#752 Improved Privacy Policy Page
  Html-Files/privacy_policy_page.html
Labels: gssoc, level3

#747 Added functionality to Daily Newsletter
  index.html
Labels: gssoc, level2

#691 Fixed "Webchat Bot" and "Scroll-to-top" Button Overlapping
  style.css
Labels: gssoc, level1

#720 Fixes #694
  index.html
  style.css
Labels: gssoc, level1

#757 removed conflicts for feature-707
  Html-Files/news.html
  index.html
Labels: gssoc, level2

#666 Added "Scroll Down Progress Bar" To The website
  Html-Files/news.html
  dex.html
  faq.html
  index.html
  style.css
Labels: gssoc, level3

#762 Update appointment.html added functionality to it
  appointment.html
Labels: gssoc, level1

#767 Added a Back-To Home Button on the Login Page
  log/login.css
  login.html
Labels: gssoc, level2

#749 Redesigned "Make an Appointment" Section
  Css-Files/appointment.css
  index.html
  style.css
Labels: gssoc, level2

#771 Github and location icon on contact page clickable
  Html-Files/contact.html
Labels: gssoc, level1

#772 Fixed Alignment Issues for Some Sections
  Css-Files/testimonial.css
  index.html
Labels: gssoc, level3

#776 feat: Improved UI Functionality and Integrate Star Rate System in the Feedback Form
  Feedback Tick.png
  index.html
  style.css
Labels: gssoc, level3

#770 Solves Issue No. 728- Unneccesary redirecting to a seperate 'Rate us' and 'Contact Us' + Routing of the navbar.
  Html-Files/Doctor Experience.html
  Html-Files/contact.html
  dex.html
  index.html
  med.html
  news.html
  rateus.css
  rateus.html
Labels: gssoc, level2

#777 Improved functionlality of appointment form
  Html-Files/appointScript.js
  Html-Files/appointment.html
Labels: gssoc, level2

#806 Added "Scroll Down Progress Bar" To The website
  Html-Files/appointment.html
  Html-Files/customer_agreement.html
  Html-Files/derma.html
  Html-Files/news.html
  Html-Files/privacy_policy_page.html
  Html-Files/terms_and_conditions.html
  test.html
Labels: gssoc, level2

#810 Add confirmation message to newsletter form
  index.html
Labels: gssoc, level2

#800 updated home page css
  index.html
Labels: gssoc, level3

#831 changed_twitter_icon
  index.html
Labels: gssoc, level1

#818 Fixed Footer Hover Text Color
  style.css
Labels: gssoc, level1

#826 Changed Internal CSS to external CSS
  index.css
  index.html
Labels: gssoc, level2

#828 ✔️Enhanced "Complete UI Design and Alignment" of the "Appointment" Page!
  Html-Files/Css-Files/appointStyle.css
  Html-Files/appointScript.js
  Html-Files/appointment.html
  assets/img/favi-Appoint.png
Labels: gssoc, level2

#835 changed the service layout
  assets/css/styles.css
  dex.html
  images/Delivery.png
  style.css
Labels: gssoc, level3

#841 add hover in social icons
  Html-Files/news.html
  index.html
  style.css
Labels: gssoc, level2

#838 improved the background of the login page
  log/login.css
  log/login.html
Labels: gssoc, level3

#855 link the login page
  index.html
Labels: gssoc, level1

#856 Changed the heading and paragraph color to make it visible
  index.css
  index.html
Labels: gssoc, level1

#878 🐞[Bug]: Fixing News.html
  .vscode/settings.json
  Css-Files/news.css
  news.html
Labels: gssoc, level3

#879 ✨[Feature Request]: Creation of Blood Test
  Html-Files/bloodtest.html
  Html-Files/bloodtest.js
  index.html
Labels: gssoc, level3

#883 add hover and size of social icons of footer in find doctor page
  Html-Files/Css-Files/Experiencestyle.css
  Html-Files/Doctor Experience.html
  style.css
Labels: gssoc, level2

#886 add hover on social icon of login
  log/login.css
  log/login.html
Labels: gssoc, level2

#889 🐞[Bug]: Fixes Unify Footer and Navbar in the Blood Test Page
  index.html
  test.css
  test.html
Labels: gssoc, level2

#890 feat/add back to top button in find doctor page
  Html-Files/Css-Files/Experiencestyle.css
  Html-Files/Doctor Experience.html
Labels: gssoc, level2

#884 Remove unnecessary br tags
  index.html
Labels: gssoc, level1

#869 added google translate button
  googletranslate.css
  googletranslate.js
  index.html
Labels: gssoc, level3

#895 made the faq page responsive
  faq.html
Labels: gssoc, level3

#901 [FEAT] : Add password visibility in login/signup
  log/login.css
  log/login.html
  log/script.js
Labels: gssoc, level2

#876 Applied Color Grading and Adde Patient Testimonial Text
  index.css
  index.html
Labels: gssoc, level1

#924 fixed the footer login bug
  index.html
Labels: gssoc, level1

#926 Fixes issue #925
  index.css
  index.html
Labels: gssoc, level1

#937 Emoji Section added in Feedback Section
  index.html
Labels: gssoc, level2

#923 🐞[Bug]: Fixes Proper alignment of Medicine.html
  Html-Files/Doctor Experience.html
  Html-Files/appointment.html
  Html-Files/blood.html
  Html-Files/bloodtest.html
  Html-Files/cardio.html
  Html-Files/customer_agreement.html
  Html-Files/derma.html
  Html-Files/doc.html
  Html-Files/ent.html
  Html-Files/gynaco.html
  Html-Files/input.html
  Html-Files/map.html
  Html-Files/pediatrition.html
  Html-Files/terms_and_conditions.html
  appointment.html
  aptmnt.html
  dex.html
  index.html
  med.html
  medicine.css
  medicine.html
  signedup.html
  successful_appointment.html
Labels: gssoc, level3

#939 Fixes screen size of small html element in every html page.
  Html-Files/Doctor Experience.html
  Html-Files/Doctor-Experience.html
  Html-Files/blood.html
  Html-Files/bloodtest.html
  Html-Files/news.html
  faq.html
  index.css
  medicine.css
  news.html
  style.css
  test.css
  test.html
Labels: gssoc, level3

#897 Feat/popup subscribe to newsletter and some bugs
  Html-Files/Css-Files/Experiencestyle.css
  Html-Files/Doctor Experience.html
  index.css
  index.html
  style.css
Labels: gssoc, level2

#943 fixes header & footer of dex.html
  dex.html
Labels: gssoc, level3

#952 Added login successful popup in patient portal
  index.html
  style.css
Labels: gssoc, level2

#953 feat: add thanks for the feed back
  index.html
  style.css
Labels: gssoc, level2

#974 Size decrement of Appointment section in index.html and nav bar text size
  index.html
Labels: gssoc, level1

#941 Update testimonial section
  Css-Files/testimonial.css
  index.html
Labels: gssoc, level3

#957 tilt effect
  dex.html
  index.css
  index.html
  js/tilt.js
  medicine.css
  medicine.html
Labels: gssoc, level3

#388 Hover effects and transform added
  style.css
Labels: gssoc, level1

#679 Adjust emergency button size for better visibility
  appointment.html
Labels: gssoc, level1

#965 Addition of button effect
  Css-Files/news.css
  Html-Files/bloodtest.html
  Html-Files/news.html
  dex.html
  index.html
  js/main.js
  medicine.css
  news.html
  style.css
Labels: gssoc, level3

#976 Addition of about us page
  .vscode/settings.json
  about.html
  images/WhatsApp Image 2024-07-23 at 18.59.53_ca6faccb.jpg
  img/WhatsApp Image 2024-07-23 at 18.59.41_52314e5b.jpg
  index.html
Labels: gssoc, level3

#824 ✔️Implemented Real Email-Sending Functionality
  index.html
Labels: gssoc, level3

#994 Fixes issue #949
  index.html
  js/script.js
  log/login.html
  log/script.js
  read.md
Labels: gssoc, level3

#985 Added refresher
  Css-Files/caduceus.css
  img/2jghCPWR6g8S6w5Nv6bF6WCSHzJ.svg
  img/Caduceus.svg.png
  index.html
  js/caduceus.js
Labels: gssoc, level3

#986 Improve Alignment and Design of the Footer
  index.html
  style.css
Labels: gssoc, level2

#980 Modified the Privacy Policy page and made it responsive .
  Html-Files/privacy_policy_page.html
Labels: gssoc, level2

#963 Added a progress bar on news page .
  news.html
Labels: gssoc, level2

#916 Enhanced the Contact Section
  index.css
  index.html
Labels: enhancement, gssoc, level2

#933 Footer hover
  assets/css/styles.css
Labels: gssoc, level1

#911 Fixed Mobile View of Contact Page
  Css-Files/aboutus.css
  index.html
  style.css
Labels: gssoc, level3

#999 Enhaced Rate Us Page
  Css-Files/Rateus.css
  index.html
  style.css
Labels: gssoc, level3

#951 Gynacologist Section Responsiveness
  Css-Files/bloodstyle.css
  Css-Files/doctor.css
Labels: gssoc, level2

#955 Fixed empty fields in registration and login page #947
  log/script.js
Labels: gssoc, level2

#1006 Movement of code to separate CSS and JS files
  - fonts.txt
  .github/workflows/Issue_template
  .github/workflows/auto-label-issues.yml
  .github/workflows/build-html-pages
  .hintrc
  Css-Files/bloodstyle.css
  Css-Files/caduceus.css
  Css-Files/doctor.css
  Css-Files/news.css
  Html-Files/Css-Files/Experiencestyle.css
  Html-Files/Css-Files/appointStyle.css
  Html-Files/Css-Files/bloodtest.css
  Html-Files/Css-Files/customer_agreement.css
  Html-Files/Doctor Experience.html
  Html-Files/Doctor-Experience.html
  Html-Files/appointment.html
  Html-Files/blood.html
  Html-Files/bloodtest.html
  Html-Files/bloodtest.js
  Html-Files/cardio.html
  Html-Files/cardio.js
  Html-Files/customer_agreement.html
  Html-Files/derma.html
  Html-Files/doc.html
  Html-Files/ent.html
  Html-Files/experience.js
  Html-Files/gynaco.html
  Html-Files/input.html
  Html-Files/map.html
  Html-Files/news.html
  Html-Files/pediatrition.html
  Html-Files/privacy_policy_page.html
  ReadMe.txt
  assets/css/styles.css
  assets/css/visitors.css
  assets/js/visitors.js
  bootstraptest.css
  chatboxx.js
  index.html
  js/backtotopjs.js
  js/caduceus.js
  js/chatbotjs.js
  js/contactpopupmessage.js
  js/date.js
  js/feedbackmessage.js
  js/footersubcribejs.js
  js/googletranslatejs.js
  js/imageswap.js
  js/loaderjs.js
  js/patientportal_loginjs.js
  js/phonejs.js
  js/progressbar_and_header.js
  js/revealelementsonscrolljsfor_index_html.js
  js/testimonalslider.js
  jsconfig.json
  style.css
  test.js
Labels: gssoc, level3

#950 Patient Section responsive
  Css-Files/patient-portal.css
  index.html
  style.css
Labels: gssoc, level3

#1015 Fixes issue #944
  Css-Files/aboutus.css
  index.css
  index.html
Labels: gssoc, level3

#853 Modified the navbar on the news page .
  Html-Files/news.html
  news.html
Labels: gssoc, level3

#899 Added responsiveness for doctor type ent
  Html-Files/ent.html
Labels: gssoc, level3

#910 Made dermatologist page responsive
  Css-Files/bloodstyle.css
  Html-Files/derma.html
Labels: gssoc, level3

#915 Made Terms & Conditions responsive
  Html-Files/terms_and_conditions.html
Labels: gssoc, level3

#1033 filename change
  assets/css/styles.css
  dex.html
Labels: gssoc, level1

#1026 Fixes issue #1022
  index.html
Labels: gssoc, level1

#1013 Added Forget password popup
  googletranslate.js
  index.css
  log/forgetpass.css
  log/forgetpass.js
  log/login.html
  log/script.js
  style.css
Labels: gssoc, level3

#1043 Fixes issue #1038
  Css-Files/doctor.css
  Html-Files/Doctor-Experience.html
  Html-Files/cardio.html
  Html-Files/derma.html
  Html-Files/ent.html
  Html-Files/gynaco.html
  Html-Files/pediatrition.html
  index.css
  index.html
  log/forgetpass.css
  log/forgetpass.js
  log/login.html
  news.html
Labels: gssoc, level3

#1052 Improved styling: flipping of cards nder about us
  index.css
  index.html
Labels: gssoc, level2

#904 Made the Book An Appointment page responsive .
  Html-Files/Css-Files/appointStyle.css
  Html-Files/appointment.html
Labels: gssoc, level3

#1051 linked the header properly from doc page
  Html-Files/Doctor Experience.html
Labels: gssoc, level1

#1011 aligned-cards
  Html-Files/Css-Files/Experiencestyle.css
Labels: gssoc, level2

#900 Made "Blood Test" Page Responsive
  style.css
  test.css
  test.html
Labels: gssoc, level3

#1060 Aligned and size decreased.
  Css-Files/Rateus.css
  index.css
  index.html
  js/emailvalidation.js
  style.css
Labels: gssoc, level2

#1053 Adding Facebook Authentication
  log/login.css
  log/login.html
Labels: gssoc, level2

#1054 Adding LinkedIn Authentication
  log/login.html
Labels: gssoc, level2

#1063 Created and Added Terms and Condition Page
  Html-Files/terms_and_conditions.html
Labels: gssoc, level3

#1055 Adding Microsoft Authentication
  log/login.html
Labels: gssoc, level2

#906 Update README.md
  README.md
Labels: gssoc, level2

#1073 Fixed the customer agreement page (Added navbar and the full footer and made the page responsive)
  Html-Files/customer_agreement.html
Labels: gssoc, level3

#896 Made the Find A Doctor/Doctor Experience page responsive .
  Html-Files/Css-Files/Experiencestyle.css
  Html-Files/Doctor Experience.html
  index.css
  log/forgetpass.css
  log/forgetpass.js
  read.md
Labels: gssoc, level3

#1074 Adding Github Authentication
  log/login.html
Labels: gssoc, level2

#1071 ✨[Feature Request]: Automatic assign
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/assignlabel.yml
  .github/workflows/auto-label-pr.yml
Labels: gssoc, level3

#971 fix Login page
  log/login.css
  log/login.html
Labels: gssoc, level2

#1017 Download Button Addition in privacy policy
  Html-Files/privacy_policy_page.html
Labels: gssoc, level2

#1075 About us section - mobile responsive
  Css-Files/aboutus.css
Labels: gssoc, level2

#1088 Updation in index file
  Css-Files/aboutus.css
  index.html
Labels: gssoc, level2
