Repository Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-, pull requests merged in 2024-08, with the labels that each got.

#1099 linked-login.html
  index.html
Labels: gssoc, level1

#1105 Enhanced the testimonials
  Css-Files/testimonial.css
  index.html
  js/testimonalslider.js
Labels: gssoc, level2

#1098 removed the appointment section from the main page
  index.html
Labels: gssoc, level1

#1085 Fixed the appoitment page (Added the navbar and the footer and made the page responsive)
  Html-Files/appointment.html
Labels: gssoc, level3

#1082 Fixing patient portal and no of visitor icon in mobile view
  index.css
  index.html
Labels: gssoc, level1

#1117 redirect to appointment page
  Html-Files/Doctor Experience.html
Labels: gssoc, level1

#1118 Updated Nav links
  Html-Files/Doctor Experience.html
  Html-Files/blood.html
  Html-Files/bloodtest.html
  Html-Files/cardio.html
  Html-Files/customer_agreement.html
  Html-Files/ent.html
  Html-Files/news.html
  Html-Files/privacy_policy_page.html
  Html-Files/terms_and_conditions.html
  checkup.html
  dex.html
  index.html
  medicine.html
  news.html
Labels: gssoc, level2

#1128 Enhanced Rate Us
  index.html
  style.css
Labels: gssoc, level3

#1032 Animated emoji Addition
  emoji1.gif
  emoji2.gif
  emoji3.gif
  emoji4.gif
  emoji5.gif
  index.html
  js/feedbackmessage.js
Labels: gssoc, level2

#1141 ✔️Added Dynamic "Last Updated" Functionality to All Legal Pages !
  Html-Files/privacy_policy_page.html
  Html-Files/terms_and_conditions.html
Labels: gssoc, level2

#1110 Fixed the testimonial section for mobile screen
  Css-Files/testimonial.css
Labels: gssoc, level1

#1115 UI of one of the cards does not match with the other cards in the news page .
  news.html
Labels: gssoc, level1

#1132 fixed navbar
  checkup.css
  index.css
  index.html
  style.css
Labels: gssoc, level2

#1145 Fixed register now button in Patient Portal
  index.html
Labels: gssoc, level1

#1149 ✔️Improved the FAQ Page ( Fixed Navbar | Made Responsive )
  faq.html
Labels: gssoc, level3

#1154 Updated the branch and added the code(bug)
  .github/workflows/auto-label-pr.yml
  Html-Files/appointment.html
Labels: gssoc, level1

#1116 Improvement of UI in Find a Doctor page
  Html-Files/Css-Files/Experiencestyle.css
  Html-Files/Doctor Experience.html
Labels: gssoc, level3

#1155 Now logo is displayed on big screen and rapidoc text on smaller screen on the news page .
  news.html
Labels: gssoc, level1

#1150 Added Hover on About Cards
  Css-Files/aboutus.css
Labels: gssoc, level1

#1125 Styled the "Sort by fee" button
  Html-Files/Doctor-Experience.html
Labels: gssoc, level1

#1126 The links in footer are not visible and look dim in the green background #1083
  assets/css/styles.css
Labels: gssoc, level1

#1163 ✨[Feature Request]: Added page
  Css-Files/helpline.css
  Html-Files/Doctor Experience.html
  Html-Files/appointment.html
  Html-Files/blood.html
  Html-Files/bloodtest.html
  Html-Files/cardio.html
  Html-Files/news.html
  dex.html
  faq.html
  helpline.html
  index.html
  js/helpline.js
  medicine.html
  portal.html
  test.html
Labels: gssoc, level3

#1167 removed the patient portal and linked it to the navbar
  index.html
Labels: gssoc, level1

#1182 Removal testimonial and security from the footer
  Html-Files/appointment.html
  Html-Files/blood.html
  Html-Files/ent.html
  Html-Files/privacy_policy_page.html
  Html-Files/terms_and_conditions.html
  index.html
  medicine.html
  test.html
Labels: gssoc, level1

#1179 created separate page for services
  dex.html
Labels: gssoc, level1

#1174 Added Terms and Conditions and Privacy Policy links
  log/login.html
Labels: gssoc, level1

#1184 ✨[Feature Request]: Added of popup
  Css-Files/helpline.css
  helpline.html
  js/helpline.js
Labels: gssoc, level2

#1186 🐞[Bug]: Decrease of font size in navbar and addition of effect the image
  index.css
  style.css
Labels: gssoc, level2
