Repository Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-, pull requests merged in 2024-05, with the labels that each got.

#100 Successful-Appointment
  index.html
  successful_appointment.html
Labels: GSSOC 2024, Level 2

#108 Revert 1 prajwaldp223 patch 1
  CODE_OF_CONDUCT.md
Labels: GSSOC 2024, Level 1

#117 Added Slack logo and link
  README.md
Labels: GSSOC 2024, Level 1

#119 Fixes: Button not responsive #116
  index.html
Labels: GSSOC 2024, Level 1

#135 Update README.md #134
  README.md
Labels: GSSOC 2024, Level 1

#136 Updated display of Doctor's image
  index.html
Labels: GSSOC 2024, Level 1

#144 Redirect to dialer pad
  index.html
Labels: bug, GSSOC 2024, Level 1

#125 Add Contact Us Page and News Section (GSSoC'24) #112
  Html-Files/Css-Files/style.css
  Html-Files/Css-Files/styles.css
  Html-Files/app.js
  Html-Files/contact.html
  Html-Files/images/1.png
  Html-Files/images/2.png
  Html-Files/images/3.png
  Html-Files/images/4.png
  Html-Files/images/5.png
  Html-Files/images/call.png
  Html-Files/images/location.png
  Html-Files/images/mail.png
  Html-Files/images/news2.png
  Html-Files/img/favicon.png
  Html-Files/news.html
  images/location.png
  index.html
Labels: gssoc, level 3

#160 Removed Social media handles in header solved issue#132
  index.html
Labels: gssoc, level 1

#185 Enable Click-to-Redirect Functionality for Contact Information Links
  index.html
Labels: gssoc, level 1

#155 Added a Customized Scrollbar to match the theme of the site.
  index.html
  style.css
Labels: gssoc, level 1

#173 Improve Navigation bar #138
  index.html
  style.css
Labels: enhancement, gssoc, level 1

#150 Improved the UI by Color Changed and various location added
  index.html
  style.css
Labels: gssoc, level 1

#226 Added pediatrician section
  Html-Files/doc.html
  img/doctors/Image(13).png
  index.html
Labels: bug, gssoc, level1

#296 Added more restrictions to Phone number and Calendar feature
  index.html
  style.css
Labels: enhancement, gssoc, level2

#336 Updated header markup to remove 'd-none' class from 'EMERGENCY' span
  index.html
Labels: gssoc, level1

#335 Read me automation branch
  README.md
Labels: gssoc, level1

#321 Fix select function
  js/main.js
Labels: gssoc, level1

#360 Add GitHub Actions Workflow for Auto Commenting on Merged PRs
  .github/workflows/auto-comment.yml
Labels: enhancement, gssoc

#356 Add Support for Deployment
  .github/workflows/build-html-pages
Labels: enhancement, gssoc

#358 Improved the layout of Featured Services Section
  style.css
Labels: gssoc, level1

#317 Added documentation file via upload
  Introduction/Advantages.md
  Introduction/Architecture.md
  Introduction/Conclusion.md
  Introduction/Disadvantages.md
  Introduction/Future Scope.md
  Introduction/Installation.md
  Introduction/Objectives.md
  Introduction/Project Overview.md
  Introduction/Technology stack.md
  Introduction/Usage.md
  Introduction/features And Services.md
  Introduction/purpose.md
Labels: gssoc, level3

#366 Proper alignment of the footer section task completed
  index.html
  style.css
Labels: gssoc, level2

#281 added navbar and footer to news.html file
  .vscode/settings.json
  Css-Files/news.css
  Html-Files/news.html
Labels: enhancement, gssoc, level3
