Repository Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-, pull requests merged in 2024-06, with the labels that each got.

#386 💡[FEATURE]: 🌟 Reveal Elements On Scroll 🌟
  index.html
Labels: gssoc, level2

#384 Added Chatbox
  chatbox.css
  chatboxx.js
  index.html
  style.css
Labels: gssoc, level3

#401 improve the PR comment workflow text: #363
  .github/workflows/greetings.yml
Labels: gssoc, level1

#403 ✨[Feature Request]: Addition of Preloader and Custom Cursor.
  index.html
Labels: gssoc, level2

#406 Logo updated
  index.html
Labels: gssoc, level1

#440 updated the info on service cards
  index.html
Labels: good first issue, gssoc, level1

#389 privacy policies file added
  Html-Files/privacy_policy_page.html
Labels: gssoc, level2

#454 twitter-logo-changed
  index.html
Labels: gssoc, level1

#449 made counts and feature section on the landing page responsive
  index.html
  style.css
Labels: gssoc, level3

#447 Enhanced About Page
  Css-Files/aboutus.css
  images/appointment.png
  images/appointmenthover.png
  images/checkup.png
  images/checkuphover.png
  images/services.png
  images/serviceshover.png
  images/ward.png
  images/wardhover.png
  index.html
Labels: enhancement, gssoc, level3

#456 Added FAQ Section
  faq.html
  index.html
Labels: gssoc, level3

#472 Corrected Patient Portal
  index.html
Labels: gssoc, level1

#464 added learn.md file
  Learn.md
Labels: gssoc, level1

#465 chatbox changes
  chatbox.css
  chatboxx.js
  index.html
Labels: bug, gssoc, level1

#430 🐞[bug]:Signup with google isn't working
  index.html
  login.html
  signedup.html
  signupjs.js
  signupjs1.js
  style.css
Labels: gssoc, level3

#485 Enhance Horizontal Scroll: Display Specific Category Doctors Only
  Html-Files/cardio.html
  Html-Files/derma.html
  Html-Files/ent.html
  Html-Files/gynaco.html
  Html-Files/pediatrition.html
  index.html
  style.css
Labels: gssoc, level3

#443 fixed overlapping
  Html-Files/Css-Files/styles.css
  index.html
  style.css
Labels: gssoc, level2

#392 Updated doctor.css
  Css-Files/doctor.css
  Html-Files/doc.html
Labels: gssoc, level1

#481 error 404 page
  Html-Files/error.css
  Html-Files/error.js
  Html-Files/error404.html
  jsconfig.json
Labels: gssoc, level2

#491 Added functionality to feedback form
  index.html
Labels: gssoc, level1

#499 Enhance the contact page
  index.html
Labels: gssoc, level2

#501 Improved the UI/UX of the website
  index.html
Labels: gssoc, level2

#507 Service and Signin/Signup changed
  index.html
  style.css
Labels: bug, gssoc, level1

#509 Removed another navbar
  index.html
Labels: gssoc, level1

#515 👩‍⚕️ Feature Request: Display Doctor Experience and Minimum Fee
  Html-Files/Css-Files/Experiencestyle.css
  Html-Files/Doctor Experience.html
  index.html
Labels: gssoc, level3

#517 🐞[Bug]: Bugs in style.css
  index.html
  style.css
Labels: gssoc, level3

#552 🐞[Bug]: Favicon and Color's
  Html-Files/Css-Files/styles.css
  Html-Files/news.html
  assets/css/styles.css
  dex.html
  index.html
  style.css
Labels: gssoc

#544 Alligned Navbar
  index.html
  style.css
Labels: gssoc, level1

#560 ✨[Feature Request]: Want to change the overall appearence of News.html file
  Html-Files/news.html
  chatbox.css
Labels: gssoc, level3

#566 Added Rate us Option
  index.html
  rateus.css
  rateus.html
  style.css
Labels: gssoc, level3

#572 Added Contact Us page detailing
  Html-Files/Css-Files/styles.css
  Html-Files/contact.html
Labels: gssoc, level3

#553 Updated find a doctor page
  Html-Files/Doctor Experience.html
  Html-Files/images/doctor17.jpeg
  Html-Files/images/doctor18.jpeg
  Html-Files/images/doctor19.jpeg
  Html-Files/images/doctor8.jpeg
Labels: gssoc, level3

#559 UI enhancement of About Us section
  Css-Files/aboutus.css
  img/asterisk.svg
  img/heart.svg
  img/question.svg
  index.html
Labels: gssoc, level2

#589 ✨[Feature Request]: Addition of GSSOC label
  .github/workflows/auto-label-issues.yml
  Html-Files/news.html
Labels: gssoc, level1

#596 all social media icons added which are missing
  Html-Files/Doctor Experience.html
  Html-Files/contact.html
  Html-Files/images/github.png
  Html-Files/images/logo.png
  Html-Files/images/mail2.png
  Html-Files/images/phone.png
  Html-Files/images/twitter.png
  Html-Files/images/twitters.png
  Html-Files/news.html
  dex.html
  index.html
  twitter.png
  twitter1.png
  twitter1.svg
Labels: gssoc, level1

#595 aligned text
  index.html
Labels: gssoc, level1

#467 feature: sending emails on newsletter subscribing
  index.html
Labels: gssoc, level2

#613 done #590
  index.html
Labels: gssoc, level1

#522 Static Documentation Site Using mkdocs
  .github/workflows/mkdocs.yaml
  mkdocs/docs/Advantages.md
  mkdocs/docs/Architecture.md
  mkdocs/docs/Conclusion.md
  mkdocs/docs/Contributing.md
  mkdocs/docs/Disadvantages.md
  mkdocs/docs/Future Scope.md
  mkdocs/docs/Installation.md
  mkdocs/docs/Objectives.md
  mkdocs/docs/Technology stack.md
  mkdocs/docs/Usage.md
  mkdocs/docs/features And Services.md
  mkdocs/docs/index.md
  mkdocs/docs/purpose.md
  mkdocs/mkdocs.yml
Labels: gssoc, level3

#603 Enhaced Rate Us Page
  index.html
  rateus.css
  rateus.html
  style.css
Labels: gssoc, level2

#520 Updatecss
  style.css
Labels: enhancement, gssoc, level1

#684 Added Functional Links to "Testimonials" and "Privacy Policy"
  index.html
Labels: gssoc, level1

#704 Made the submit button functional
  index.html
  style.css
Labels: gssoc, level2

#634 News Page is been changed with Animated Buttons
  Html-Files/news.html
Labels: enhancement, gssoc, level3

#642 All changes done in avatar,input and submit button
  index.html
Labels: gssoc, level1

#724 Database Support for forms and various registrations
  assets/DbSchema101.png
Labels: gssoc, level3
